### ISSUE TITLE
这个svg的path有三个，最终转换后丢了两个，只有一个了

### ISSUE THREAD

**Issue by superchangme** [335296558/vite-plugin-vue-svg-icons#1]
<?xml version="1.0" standalone="no"?>
<svg t="1645689220021" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2083" width="24" height="24" xmlns:xlink="http://www.w3.org/1999/xlink">
<path d="M712.248889 726.471111l-1.820445-91.704889a24.917333 24.917333 0 0 1 24.974223-25.429333c14.222222 0 25.827556 11.207111 26.339555 25.429333l1.422222 40.789334h53.873778a25.429333 25.429333 0 0 1 0 50.858666h-104.732444zM393.500444 768a28.444444 28.444444 0 1 1 0 56.888889H341.333333A199.111111 199.111111 0 0 1 142.222222 625.777778V341.333333A199.111111 199.111111 0 0 1 341.333333 142.222222h341.333334A199.111111 199.111111 0 0 1 881.777778 341.333333v86.357334a28.444444 28.444444 0 1 1-56.888889 0V341.333333A142.222222 142.222222 0 0 0 682.666667 199.111111H341.333333A142.222222 142.222222 0 0 0 199.111111 341.333333v284.444445A142.222222 142.222222 0 0 0 341.333333 768h52.167111z" p-id="2084" fill="#9CA4BA"></path>
<path d="M341.333333 335.587556m28.444445 0l284.444444 0q28.444444 0 28.444445 28.444444l0 0q0 28.444444-28.444445 28.444444l-284.444444 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444444Z" p-id="2085" fill="#9CA4BA"></path>
<path d="M341.333333 455.111111m28.444445 0l113.777778 0q28.444444 0 28.444444 28.444445l0 0q0 28.444444-28.444444 28.444444l-113.777778 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444445Z" p-id="2086" fill="#9CA4BA"></path><path d="M745.244444 492.999111c109.283556 0 199.111111 89.770667 199.111112 199.111111 0 109.283556-89.827556 199.111111-199.111112 199.111111a199.964444 199.964444 0 0 1-199.111111-199.111111c0-109.340444 89.827556-199.111111 199.111111-199.111111z m0 56.888889a143.075556 143.075556 0 0 0-142.222222 142.222222c0 77.880889 64.341333 142.222222 142.222222 142.222222 77.937778 0 142.222222-64.341333 142.222223-142.222222 0-77.937778-64.284444-142.222222-142.222223-142.222222z" p-id="2087" fill="#9CA4BA">
</path>
</svg>

**Comment by superchangme** [comment]
<?xml version="1.0" standalone="no"?>
<svg t="1645689220021" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2083" width="24" height="24" xmlns:xlink="http://www.w3.org/1999/xlink">
<path d="M712.248889 726.471111l-1.820445-91.704889a24.917333 24.917333 0 0 1 24.974223-25.429333c14.222222 0 25.827556 11.207111 26.339555 25.429333l1.422222 40.789334h53.873778a25.429333 25.429333 0 0 1 0 50.858666h-104.732444zM393.500444 768a28.444444 28.444444 0 1 1 0 56.888889H341.333333A199.111111 199.111111 0 0 1 142.222222 625.777778V341.333333A199.111111 199.111111 0 0 1 341.333333 142.222222h341.333334A199.111111 199.111111 0 0 1 881.777778 341.333333v86.357334a28.444444 28.444444 0 1 1-56.888889 0V341.333333A142.222222 142.222222 0 0 0 682.666667 199.111111H341.333333A142.222222 142.222222 0 0 0 199.111111 341.333333v284.444445A142.222222 142.222222 0 0 0 341.333333 768h52.167111z" p-id="2084" fill="#9CA4BA"></path>
<path d="M341.333333 335.587556m28.444445 0l284.444444 0q28.444444 0 28.444445 28.444444l0 0q0 28.444444-28.444445 28.444444l-284.444444 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444444Z" p-id="2085" fill="#9CA4BA"></path>
<path d="M341.333333 455.111111m28.444445 0l113.777778 0q28.444444 0 28.444444 28.444445l0 0q0 28.444444-28.444444 28.444444l-113.777778 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444445Z" p-id="2086" fill="#9CA4BA"></path><path d="M745.244444 492.999111c109.283556 0 199.111111 89.770667 199.111112 199.111111 0 109.283556-89.827556 199.111111-199.111112 199.111111a199.964444 199.964444 0 0 1-199.111111-199.111111c0-109.340444 89.827556-199.111111 199.111111-199.111111z m0 56.888889a143.075556 143.075556 0 0 0-142.222222 142.222222c0 77.880889 64.341333 142.222222 142.222222 142.222222 77.937778 0 142.222222-64.341333 142.222223-142.222222 0-77.937778-64.284444-142.222222-142.222223-142.222222z" p-id="2087" fill="#9CA4BA">
</path>
</svg>

**Comment by superchangme** [comment]
&lt;?xml version=&quot;1.0&quot; standalone=&quot;no&quot;?&gt;
&lt;svg t=&quot;1645689220021&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;2083&quot; width=&quot;24&quot; height=&quot;24&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
&lt;path d=&quot;M712.248889 726.471111l-1.820445-91.704889a24.917333 24.917333 0 0 1 24.974223-25.429333c14.222222 0 25.827556 11.207111 26.339555 25.429333l1.422222 40.789334h53.873778a25.429333 25.429333 0 0 1 0 50.858666h-104.732444zM393.500444 768a28.444444 28.444444 0 1 1 0 56.888889H341.333333A199.111111 199.111111 0 0 1 142.222222 625.777778V341.333333A199.111111 199.111111 0 0 1 341.333333 142.222222h341.333334A199.111111 199.111111 0 0 1 881.777778 341.333333v86.357334a28.444444 28.444444 0 1 1-56.888889 0V341.333333A142.222222 142.222222 0 0 0 682.666667 199.111111H341.333333A142.222222 142.222222 0 0 0 199.111111 341.333333v284.444445A142.222222 142.222222 0 0 0 341.333333 768h52.167111z&quot; p-id=&quot;2084&quot; fill=&quot;#9CA4BA&quot;&gt;&lt;/path&gt;
&lt;path d=&quot;M341.333333 335.587556m28.444445 0l284.444444 0q28.444444 0 28.444445 28.444444l0 0q0 28.444444-28.444445 28.444444l-284.444444 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444444Z&quot; p-id=&quot;2085&quot; fill=&quot;#9CA4BA&quot;&gt;&lt;/path&gt;
&lt;path d=&quot;M341.333333 455.111111m28.444445 0l113.777778 0q28.444444 0 28.444444 28.444445l0 0q0 28.444444-28.444444 28.444444l-113.777778 0q-28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444445Z&quot; p-id=&quot;2086&quot; fill=&quot;#9CA4BA&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M745.244444 492.999111c109.283556 0 199.111111 89.770667 199.111112 199.111111 0 109.283556-89.827556 199.111111-199.111112 199.111111a199.964444 199.964444 0 0 1-199.111111-199.111111c0-109.340444 89.827556-199.111111 199.111111-199.111111z m0 56.888889a143.075556 143.075556 0 0 0-142.222222 142.222222c0 77.880889 64.341333 142.222222 142.222222 142.222222 77.937778 0 142.222222-64.341333 142.222223-142.222222 0-77.937778-64.284444-142.222222-142.222223-142.222222z&quot; p-id=&quot;2087&quot; fill=&quot;#9CA4BA&quot;&gt;
&lt;/path&gt;
&lt;/svg&gt;

**Comment by 335296558** [comment]
> <?xml version="1.0" Standalone="no"?> <svg t="1645689220021" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns=" [http://www.w3 .org/2000/svg](http://www.w3.org/2000/svg) " p-id="2083" width="24" height="24" xmlns:xlink=" http://www.w3.org/1999/xlink "> <路径d =“M712.248889726.471111升-1.820445-91.704889a24.917333 24.917333 0 0 1 0 24.974223-25.429333c14.222222 25.827556 11.207111 26.339555 25.429333l1.422222 40.789334h53.873778a25.429333 25.429333 0 0 1 0 50.858666h-104.732444 zM393.500444 768a28.444444 28.444444 0 1 1 0 56.888889H341.333333A199.111111 199.111111 0 0 1 142.222222 625.777778V341.333333A199.111111 199.111111 0 0 1 341.333333 142.222222h341.333334A199.111111 199.111111 0 0 1 881.777778 341.333333v86.357334a28.444444 28.444444 0 1 1-56.888889 0V341.333333A142.222222 142.222222 0 0 0 682.666667 199.111111H341.333333A142.222222 142.222222 0 0 0 199.111111 341.333333v284.444445A142.222222 142.222222 0 0 0 341.333333 768h52.167111z” p-ID = “2084” 填充="#9CA4BA"></路径> <路径d = “M341.333333 335.587556m28.444445 0l284.444444 0q28.444444 0 28.444445 28.444444l0 0q0 28.444444-28.44444528.444444升-284.444444 0q28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444444Z” P-ID ="2085" 填充="#9CA4BA"></path> <路径d = “M341.333333 455.111111m28.444445 0l113.777778 0q28.444444 0 28.444444 28.444445l0 0q0 28.444444-28.44444428.444444升-113.777778 0q28.444444 0-28.444445-28.444444l0 0q0-28.444444 28.444445-28.444445Z” P-ID = “2086”填充= “＃9CA4BA”> </路径> <路径d =“M745.244444 492.999111c109.283556 0 199.111111 89.770667 199.111112 199.111111 0 109.283556-89.827556 199.111111-199.111112 199.111111a199.964444 199.964444 0 0 1-199.111111- 199.111111c0-109.340444 89.827556-199.111111 199.111111-199.111111z M0 56.888889a143.075556 143.075556 0 0 0-142.222222 142.222222c0 77.880889 64.341333 142.222222 142.222222 142.222222 77.937778 0 142.222222-64.341333 142.222223-142.222222 0-77.937778-64.284444-142.222222-142.222223-142.222222z” p-id="2087" 填充="#9CA4BA"> </路径> </svg>

**Comment by 335296558** [comment]
感谢你的反馈，我尽快修复

**Comment by superchangme** [comment]
svgStr = svgStr.replace(/fill="[\s\S]*" /g, `fill="${option.color}" `)

19行这行代码改一下，就可以了
    svgStr = svgStr.replace(/fill="[\s\S]+?" /g, `fill="${option.color}" `)

**Comment by 335296558** [comment]
已经修复了

**Comment by gangguo** [comment]
优秀
