### ISSUE TITLE
有的svg图片path有多种颜色会被错误替换掉

### ISSUE THREAD

**Issue by superchangme** [335296558/vite-plugin-vue-svg-icons#2]
是否可以加入一个props开关，convertColor=false这样的

**Comment by 335296558** [comment]
你的提议不错，确实应该支持不干涉svg原本的默认色。我处理一下

**Comment by 335296558** [comment]
> 是否可以加入一个道具开关，convertColor=false这样的
版本更新了，不过我的方案是，不传color 就不干涉svg原本的默认色。
多色的情况，不传color就可以了

**Comment by superchangme** [comment]
大佬，还有个问题，svg里的class会全局污染，是否能够用svg use再包裹一层呢

**Comment by 335296558** [comment]
> 大佬，还有个问题，svg里的class会全局污染，是否能够用svg use再包裹一层呢

嗯，这是一个问题，我再优化一下

**Comment by 335296558** [comment]
> > 大佬，还有个问题，svg里的class会全局污染，是否能够用svg use再包裹一层呢
> 
> 嗯，这是一个问题，我再优化一下
use暂时不考滤再包裹一层咯！
svg 里的class 并非插件定义的，是svg原本自带的，svg 不应该设置class, 有样式需求应该在外面包一层来处来哦

**Comment by 335296558** [comment]
> > > 大佬，还有个问题，svg里的class会全局污染，是否能够用svg use再包裹一层呢
> > 
> > 
> > 嗯，这是一个问题，我再优化一下

use暂时不考滤再包裹一层咯！
svg 里的class 并非插件定义的，是svg原本自带的，svg 不应该设置class, 有样式需求应该在外面包一层来处来哦
