### ISSUE TITLE
svg size不能被正确设置

### ISSUE THREAD

**Issue by superchangme** [335296558/vite-plugin-vue-svg-icons#3]
如果svg内部有path写了with 就会导致svg的size属性失效

**Comment by superchangme** [comment]
index.js 20行修改一下就好

```
  if (svgStr.indexOf('width="')<0) {
       svgStr.replace(/<svg([^>]+)/g, `<svg $1 width="${option.size}"`)
    }
    if (svgStr.indexOf('height="')<0) {
       svgStr.replace(/<svg([^>]+)/g, `<svg $1 height="${option.size}"`)
    }

```

**Comment by superchangme** [comment]
dist/index.js 20行修改一下 就可以了
```
 let svgStartTag = svgStr.match(/<svg([^>]+)/g)[0]
    if (svgStartTag.indexOf('width="')<0) {
        svgStr = svgStr.replace(/<svg/g, `<svg width="${option.size}"`)
    }
    if (svgStartTag.indexOf('height="')<0) {
        svgStr = svgStr.replace(/<svg/g, `<svg height="${option.size}"`)
    }
```

**Comment by 335296558** [comment]
> 如果svg内部有path写了with 就会导致svg的size属性失效

能截图一下你这个svg的path width 那部份上来吗？因为我需测试

**Comment by 335296558** [comment]
> 如果svg内部有path写了with 就会导致svg的size属性失效

**Comment by 335296558** [comment]
> 如果svg内部有path写了with 就会导致svg的size属性失效
svg 原本不带width、height 的情况是会导这个情况，将采用你的方案兼容这种情况

**Comment by superchangme** [comment]
<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 80 80" style="enable-background:new 0 0 80 80;" xml:space="preserve">
<g>
	<circle class="st0" cx="203" cy="47.1" r="50"/>
	<g>
		<rect x="181.2" y="23.1" class="st1" width="43.6" height="43.6"/>
		<path class="st2" d="M219.7,32.2c-3.3,0-9.2-0.8-14.3-5.8c-0.9-0.9-2.3-1-3.3-0.2c-2.6,2.1-8.1,5.6-14.8,5.8
			c-1.4,0-2.4,1.2-2.4,2.5v15.8c0,3.2-0.2,10.3,17.5,20.4c0.7,0.4,1.6,0.4,2.4,0.1c17.4-8.7,17.5-16.2,17.5-19.1v-17
			C222.2,33.3,221.1,32.2,219.7,32.2L219.7,32.2z M211.6,49.5l-8.7,9c-0.5,0.5-1.1,0.7-1.7,0.7c-0.6,0-1.1-0.2-1.6-0.6
			c-0.9-0.9-0.9-2.3-0.1-3.2l4.9-5.2h-7.4c-0.9,0-1.8-0.6-2.1-1.4c-0.4-0.9-0.2-1.8,0.5-2.5l8.1-8.1c0.9-0.9,2.3-0.9,3.2,0
			c0.9,0.9,0.9,2.3,0,3.2l-4.2,4.2h7.2c0.9,0,1.7,0.5,2.1,1.4C212.4,47.8,212.2,48.8,211.6,49.5L211.6,49.5z M211.6,49.5"/>
		<path class="st3" d="M222.2,41.3v-6.5c0-1.4-1.1-2.5-2.5-2.5c-3.3,0-9.2-0.8-14.3-5.8c-0.9-0.9-2.3-1-3.3-0.2
			c-2.6,2.1-8.1,5.6-14.8,5.8c-1.4,0-2.4,1.2-2.4,2.5v15.8c0,2.7-0.1,8,10,15.5C208.5,64.6,219.5,54.4,222.2,41.3L222.2,41.3z
			 M195.6,46.3l8.1-8.1c0.9-0.9,2.3-0.9,3.2,0c0.9,0.9,0.9,2.3,0,3.2l-4.2,4.2h7.2c0.9,0,1.7,0.5,2.1,1.4c0.4,0.8,0.2,1.8-0.5,2.5
			l-8.7,9c-0.5,0.5-1.1,0.7-1.7,0.7c-0.6,0-1.1-0.2-1.6-0.6c-0.9-0.9-0.9-2.3-0.1-3.2l4.9-5.2h-7.4c-0.9,0-1.8-0.6-2.1-1.4
			C194.7,47.9,194.9,46.9,195.6,46.3L195.6,46.3z M195.6,46.3"/>
	</g>
</g>
<g>
	<circle class="st4" cx="46.1" cy="205.9" r="50"/>
	<g>
		<g>
			<path class="st5" d="M59.8,188.1h-6.2c0,2.4-2,4.4-4.4,4.4h-6c-2.4,0-4.4-2-4.4-4.4h-6.2c-2.5,0-4.4,2-4.4,4.4v32.9
				c0,2.5,2,4.4,4.4,4.4h27.3c2.5,0,4.4-2,4.4-4.4v-32.9C64.2,190.1,62.2,188.1,59.8,188.1z"/>
			<path class="st5" d="M53.6,188v-1.7c0-2.5-2-4.4-4.4-4.4h-6c-2.5,0-4.4,2-4.4,4.4v1.7c0,0,0,0,0,0.1L53.6,188
				C53.6,188.1,53.6,188,53.6,188z"/>
			<path class="st6" d="M43.1,192.5h6c2.4,0,4.4-2,4.4-4.4H38.7C38.7,190.5,40.7,192.5,43.1,192.5z"/>
		</g>
		<path class="st7" d="M33.9,229.8c27.9-1,30.1-24.6,30.1-24.6s0,0,0.1,0.1v-12.8c0-2.5-2-4.4-4.4-4.4h-6.2c0,2.4-2,4.4-4.4,4.4h-6
			c-2.4,0-4.4-2-4.4-4.4h-6.2c-2.5,0-4.4,2-4.4,4.4v32.9c0,2.5,2,4.4,4.4,4.4L33.9,229.8C34,229.9,33.9,229.8,33.9,229.8z"/>
		<path class="st4" d="M29.3,210.4"/>
		<path class="st8" d="M44.5,217.7c-0.6,0-1.1-0.2-1.6-0.6l-6.5-6.5c-0.9-0.9-0.9-2.3,0-3.1c0.4-0.4,1-0.6,1.6-0.6
			c0.6,0,1.1,0.2,1.6,0.6l3.7,3.7c0.3,0.3,0.8,0.5,1.3,0.5s0.9-0.2,1.3-0.5l7.8-7.8c0.4-0.4,1-0.6,1.6-0.6c0.6,0,1.1,0.2,1.6,0.6
			c0.4,0.4,0.6,1,0.6,1.6c0,0.6-0.2,1.1-0.6,1.6L46.1,217C45.7,217.4,45.1,217.7,44.5,217.7z"/>
	</g>
</g>
<circle class="st9" cx="40" cy="40" r="40"/>
<g>
	<path class="st10" d="M32.2,19c-1,0-1.9,0.8-1.9,1.9v2.2h0v2.4c0,1,0.8,1.9,1.9,1.9s1.9-0.8,1.9-1.9v-2.4h0v-2.2h0
		C34.1,19.8,33.2,19,32.2,19z"/>
	<path class="st10" d="M48.3,20.9c0-1-0.8-1.9-1.9-1.9c-1,0-1.9,0.8-1.9,1.9v2.2h0v2.4c0,1,0.8,1.9,1.9,1.9c1,0,1.9-0.8,1.9-1.9
		v-2.4h0L48.3,20.9L48.3,20.9z"/>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"/>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"/>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"/>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"/>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"/>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"/>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"/>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"/>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"/>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"/>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"/>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"/>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"/>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"/>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"/>
	<path class="st10" d="M53.3,46.2c-1.6-1.7-3.8-2.8-6.3-2.8c-0.9,0-1.7,0.1-2.5,0.4c-0.8,0.2-1.5,0.6-2.2,1.1
		c-0.5,0.3-0.9,0.7-1.3,1c-0.2,0.2-0.4,0.4-0.5,0.6c-0.3,0.4-0.7,0.9-0.9,1.4c-0.7,1.2-1,2.6-1,4c0,2.6,1.1,4.9,3,6.4
		c1.5,1.3,3.4,2.1,5.5,2.1c4.7,0,8.5-3.8,8.5-8.5C55.5,49.8,54.7,47.7,53.3,46.2z M48.7,52.7c0,0.8-0.6,1.4-1.4,1.4H44
		c-0.8,0-1.4-0.6-1.4-1.4c0-0.8,0.6-1.4,1.4-1.4H46v-3.6c0-0.8,0.6-1.4,1.4-1.4c0.8,0,1.4,0.6,1.4,1.4L48.7,52.7z"/>
	<path class="st10" d="M51,23.1h-0.7l0,2h0v0.4c0,2.1-1.7,3.9-3.9,3.9c-2.1,0-3.9-1.7-3.9-3.9v-2.4h-6.5l0,2h0v0.4
		c0,2.1-1.7,3.9-3.9,3.9c-2.1,0-3.9-1.7-3.9-3.9v-2.4h-0.7c-2.1,0-3.8,1.7-3.8,3.8v29.3c0,2.1,1.7,3.8,3.8,3.8h12.6
		C38,58,36.6,55.1,36.6,52c0-1.8,0.5-3.5,1.3-5c0.3-0.6,0.7-1.1,1.1-1.7c0.2-0.3,0.4-0.5,0.7-0.7c0.5-0.5,1-0.9,1.5-1.3
		c0.8-0.6,1.8-1,2.7-1.3c1-0.3,2-0.5,3.1-0.5c3,0,5.8,1.3,7.7,3.4V26.9C54.7,24.8,53.1,23.1,51,23.1z M37.9,44.7h-7.4
		c-0.9,0-1.7-0.8-1.7-1.7c0-0.9,0.8-1.7,1.7-1.7h7.4c0.9,0,1.7,0.8,1.7,1.7C39.6,43.9,38.9,44.7,37.9,44.7z M48.5,36.5H30.5
		c-0.9,0-1.7-0.8-1.7-1.7c0-0.9,0.8-1.7,1.7-1.7h17.9c0.9,0,1.7,0.8,1.7,1.7C50.1,35.7,49.4,36.5,48.5,36.5z"/>
</g>
</svg>

**Comment by superchangme** [comment]
`<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 80 80" style="enable-background:new 0 0 80 80;" xml:space="preserve">
<g>
	<circle class="st0" cx="203" cy="47.1" r="50"></circle>
	<g>
		<rect x="181.2" y="23.1" class="st1" width="43.6" height="43.6"></rect>
		<path class="st2" d="M219.7,32.2c-3.3,0-9.2-0.8-14.3-5.8c-0.9-0.9-2.3-1-3.3-0.2c-2.6,2.1-8.1,5.6-14.8,5.8
			c-1.4,0-2.4,1.2-2.4,2.5v15.8c0,3.2-0.2,10.3,17.5,20.4c0.7,0.4,1.6,0.4,2.4,0.1c17.4-8.7,17.5-16.2,17.5-19.1v-17
			C222.2,33.3,221.1,32.2,219.7,32.2L219.7,32.2z M211.6,49.5l-8.7,9c-0.5,0.5-1.1,0.7-1.7,0.7c-0.6,0-1.1-0.2-1.6-0.6
			c-0.9-0.9-0.9-2.3-0.1-3.2l4.9-5.2h-7.4c-0.9,0-1.8-0.6-2.1-1.4c-0.4-0.9-0.2-1.8,0.5-2.5l8.1-8.1c0.9-0.9,2.3-0.9,3.2,0
			c0.9,0.9,0.9,2.3,0,3.2l-4.2,4.2h7.2c0.9,0,1.7,0.5,2.1,1.4C212.4,47.8,212.2,48.8,211.6,49.5L211.6,49.5z M211.6,49.5"></path>
		<path class="st3" d="M222.2,41.3v-6.5c0-1.4-1.1-2.5-2.5-2.5c-3.3,0-9.2-0.8-14.3-5.8c-0.9-0.9-2.3-1-3.3-0.2
			c-2.6,2.1-8.1,5.6-14.8,5.8c-1.4,0-2.4,1.2-2.4,2.5v15.8c0,2.7-0.1,8,10,15.5C208.5,64.6,219.5,54.4,222.2,41.3L222.2,41.3z
			 M195.6,46.3l8.1-8.1c0.9-0.9,2.3-0.9,3.2,0c0.9,0.9,0.9,2.3,0,3.2l-4.2,4.2h7.2c0.9,0,1.7,0.5,2.1,1.4c0.4,0.8,0.2,1.8-0.5,2.5
			l-8.7,9c-0.5,0.5-1.1,0.7-1.7,0.7c-0.6,0-1.1-0.2-1.6-0.6c-0.9-0.9-0.9-2.3-0.1-3.2l4.9-5.2h-7.4c-0.9,0-1.8-0.6-2.1-1.4
			C194.7,47.9,194.9,46.9,195.6,46.3L195.6,46.3z M195.6,46.3"></path>
	</g>
</g>
<g>
	<circle class="st4" cx="46.1" cy="205.9" r="50"></circle>
	<g>
		<g>
			<path class="st5" d="M59.8,188.1h-6.2c0,2.4-2,4.4-4.4,4.4h-6c-2.4,0-4.4-2-4.4-4.4h-6.2c-2.5,0-4.4,2-4.4,4.4v32.9
				c0,2.5,2,4.4,4.4,4.4h27.3c2.5,0,4.4-2,4.4-4.4v-32.9C64.2,190.1,62.2,188.1,59.8,188.1z"></path>
			<path class="st5" d="M53.6,188v-1.7c0-2.5-2-4.4-4.4-4.4h-6c-2.5,0-4.4,2-4.4,4.4v1.7c0,0,0,0,0,0.1L53.6,188
				C53.6,188.1,53.6,188,53.6,188z"></path>
			<path class="st6" d="M43.1,192.5h6c2.4,0,4.4-2,4.4-4.4H38.7C38.7,190.5,40.7,192.5,43.1,192.5z"></path>
		</g>
		<path class="st7" d="M33.9,229.8c27.9-1,30.1-24.6,30.1-24.6s0,0,0.1,0.1v-12.8c0-2.5-2-4.4-4.4-4.4h-6.2c0,2.4-2,4.4-4.4,4.4h-6
			c-2.4,0-4.4-2-4.4-4.4h-6.2c-2.5,0-4.4,2-4.4,4.4v32.9c0,2.5,2,4.4,4.4,4.4L33.9,229.8C34,229.9,33.9,229.8,33.9,229.8z"></path>
		<path class="st4" d="M29.3,210.4"></path>
		<path class="st8" d="M44.5,217.7c-0.6,0-1.1-0.2-1.6-0.6l-6.5-6.5c-0.9-0.9-0.9-2.3,0-3.1c0.4-0.4,1-0.6,1.6-0.6
			c0.6,0,1.1,0.2,1.6,0.6l3.7,3.7c0.3,0.3,0.8,0.5,1.3,0.5s0.9-0.2,1.3-0.5l7.8-7.8c0.4-0.4,1-0.6,1.6-0.6c0.6,0,1.1,0.2,1.6,0.6
			c0.4,0.4,0.6,1,0.6,1.6c0,0.6-0.2,1.1-0.6,1.6L46.1,217C45.7,217.4,45.1,217.7,44.5,217.7z"></path>
	</g>
</g>
<circle class="st9" cx="40" cy="40" r="40"></circle>
<g>
	<path class="st10" d="M32.2,19c-1,0-1.9,0.8-1.9,1.9v2.2h0v2.4c0,1,0.8,1.9,1.9,1.9s1.9-0.8,1.9-1.9v-2.4h0v-2.2h0
		C34.1,19.8,33.2,19,32.2,19z"></path>
	<path class="st10" d="M48.3,20.9c0-1-0.8-1.9-1.9-1.9c-1,0-1.9,0.8-1.9,1.9v2.2h0v2.4c0,1,0.8,1.9,1.9,1.9c1,0,1.9-0.8,1.9-1.9
		v-2.4h0L48.3,20.9L48.3,20.9z"></path>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"></path>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"></path>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"></path>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"></path>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"></path>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"></path>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"></path>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"></path>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"></path>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"></path>
	<path class="st1" d="M39,45.3c-0.4,0.5-0.8,1.1-1.1,1.7C38.2,46.4,38.6,45.9,39,45.3z"></path>
	<path class="st1" d="M30.5,36.5h17.9c0.9,0,1.7-0.8,1.7-1.7c0-0.9-0.8-1.7-1.7-1.7H30.5c-0.9,0-1.7,0.8-1.7,1.7
		C28.9,35.7,29.6,36.5,30.5,36.5z"></path>
	<path class="st1" d="M41.2,43.3c-0.6,0.4-1.1,0.8-1.5,1.3C40.1,44.1,40.7,43.7,41.2,43.3z"></path>
	<path class="st1" d="M39.6,43c0-0.9-0.8-1.7-1.7-1.7h-7.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h7.4
		C38.9,44.7,39.6,43.9,39.6,43z"></path>
	<path class="st1" d="M47.4,45.1c-0.9,0-1.7,0.8-1.7,1.7v4.4h-2.4c-0.9,0-1.7,0.8-1.7,1.7c0,0.9,0.8,1.7,1.7,1.7h4.1
		c0.9,0,1.7-0.8,1.7-1.7v-6.1C49.1,45.9,48.3,45.1,47.4,45.1z"></path>
	<path class="st10" d="M53.3,46.2c-1.6-1.7-3.8-2.8-6.3-2.8c-0.9,0-1.7,0.1-2.5,0.4c-0.8,0.2-1.5,0.6-2.2,1.1
		c-0.5,0.3-0.9,0.7-1.3,1c-0.2,0.2-0.4,0.4-0.5,0.6c-0.3,0.4-0.7,0.9-0.9,1.4c-0.7,1.2-1,2.6-1,4c0,2.6,1.1,4.9,3,6.4
		c1.5,1.3,3.4,2.1,5.5,2.1c4.7,0,8.5-3.8,8.5-8.5C55.5,49.8,54.7,47.7,53.3,46.2z M48.7,52.7c0,0.8-0.6,1.4-1.4,1.4H44
		c-0.8,0-1.4-0.6-1.4-1.4c0-0.8,0.6-1.4,1.4-1.4H46v-3.6c0-0.8,0.6-1.4,1.4-1.4c0.8,0,1.4,0.6,1.4,1.4L48.7,52.7z"></path>
	<path class="st10" d="M51,23.1h-0.7l0,2h0v0.4c0,2.1-1.7,3.9-3.9,3.9c-2.1,0-3.9-1.7-3.9-3.9v-2.4h-6.5l0,2h0v0.4
		c0,2.1-1.7,3.9-3.9,3.9c-2.1,0-3.9-1.7-3.9-3.9v-2.4h-0.7c-2.1,0-3.8,1.7-3.8,3.8v29.3c0,2.1,1.7,3.8,3.8,3.8h12.6
		C38,58,36.6,55.1,36.6,52c0-1.8,0.5-3.5,1.3-5c0.3-0.6,0.7-1.1,1.1-1.7c0.2-0.3,0.4-0.5,0.7-0.7c0.5-0.5,1-0.9,1.5-1.3
		c0.8-0.6,1.8-1,2.7-1.3c1-0.3,2-0.5,3.1-0.5c3,0,5.8,1.3,7.7,3.4V26.9C54.7,24.8,53.1,23.1,51,23.1z M37.9,44.7h-7.4
		c-0.9,0-1.7-0.8-1.7-1.7c0-0.9,0.8-1.7,1.7-1.7h7.4c0.9,0,1.7,0.8,1.7,1.7C39.6,43.9,38.9,44.7,37.9,44.7z M48.5,36.5H30.5
		c-0.9,0-1.7-0.8-1.7-1.7c0-0.9,0.8-1.7,1.7-1.7h17.9c0.9,0,1.7,0.8,1.7,1.7C50.1,35.7,49.4,36.5,48.5,36.5z"></path>
</g>
</svg>`

**Comment by 335296558** [comment]
> 如果svg内部有path写了with 就会导致svg的size属性失效

**Comment by 335296558** [comment]
1.1.3版本修复了该问题

**Comment by 335296558** [comment]
> 如果svg内部有path写了with 就会导致svg的size属性失效

1.1.3版本修复了该问题

**Comment by 335296558** [comment]
1.1.3版本修复了该问题

**Comment by 335296558** [comment]
1.1.3版本修复了该问题

**Comment by 335296558** [comment]
1.1.3版本修复了该问题
