### ISSUE TITLE
现在有一种场景是svg元素不需要设置宽高

### ISSUE THREAD

**Issue by superchangme** [335296558/vite-plugin-vue-svg-icons#4]
由于插件有默认的size，导致以下svg的rect被错误替换了，能否加入一个参数跳过设置宽高呢，或者size不要给默认值？
`<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
<rect x="0.5" y="0.5" class="st0" width="15" height="15"/>
<path class="st1" d="M8.7,3.6l1,2C9.7,5.7,9.9,5.8,10,5.9l2.2,0.3c0.4,0.1,0.5,0.5,0.2,0.7l-1.6,1.6c-0.1,0.1-0.1,0.2-0.1,0.4
	l0.4,2.2c0.1,0.4-0.3,0.6-0.6,0.5l-2-1.1c-0.1-0.1-0.3-0.1-0.4,0l-2,1.1c-0.3,0.2-0.7-0.1-0.6-0.5l0.4-2.2c0-0.1,0-0.3-0.1-0.4
	L4.1,6.9C3.8,6.7,3.9,6.2,4.3,6.2l2.2-0.3c0.1,0,0.3-0.1,0.3-0.2l1-2C8,3.3,8.5,3.3,8.7,3.6z"/>
</svg>`

**Comment by 335296558** [comment]
> 由于插件有默认的size，导致以下svg的rect被错误替换了，能否加入一个参数跳过设置宽高呢，或者size不要给默认值？ `<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve"> <rect x="0.5" y="0.5" class="st0" width="15" height="15"/> <path class="st1" d="M8.7,3.6l1,2C9.7,5.7,9.9,5.8,10,5.9l2.2,0.3c0.4,0.1,0.5,0.5,0.2,0.7l-1.6,1.6c-0.1,0.1-0.1,0.2-0.1,0.4 l0.4,2.2c0.1,0.4-0.3,0.6-0.6,0.5l-2-1.1c-0.1-0.1-0.3-0.1-0.4,0l-2,1.1c-0.3,0.2-0.7-0.1-0.6-0.5l0.4-2.2c0-0.1,0-0.3-0.1-0.4 L4.1,6.9C3.8,6.7,3.9,6.2,4.3,6.2l2.2-0.3c0.1,0,0.3-0.1,0.3-0.2l1-2C8,3.3,8.5,3.3,8.7,3.6z"/> </svg>`

处理了，svg的rect的宽高度不会再被改变，你更新一下1.1.4版本

**Comment by 335296558** [comment]
> 

svg 没有宽高就不会显示了吧？

**Comment by 335296558** [comment]
> 由于插件有默认的size，导致以下svg的rect被错误替换了，能否加入一个参数跳过设置宽高呢，或者size不要给默认值？ `<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve"> <rect x="0.5" y="0.5" class="st0" width="15" height="15"/> <path class="st1" d="M8.7,3.6l1,2C9.7,5.7,9.9,5.8,10,5.9l2.2,0.3c0.4,0.1,0.5,0.5,0.2,0.7l-1.6,1.6c-0.1,0.1-0.1,0.2-0.1,0.4 l0.4,2.2c0.1,0.4-0.3,0.6-0.6,0.5l-2-1.1c-0.1-0.1-0.3-0.1-0.4,0l-2,1.1c-0.3,0.2-0.7-0.1-0.6-0.5l0.4-2.2c0-0.1,0-0.3-0.1-0.4 L4.1,6.9C3.8,6.7,3.9,6.2,4.3,6.2l2.2-0.3c0.1,0,0.3-0.1,0.3-0.2l1-2C8,3.3,8.5,3.3,8.7,3.6z"/> </svg>`

svg 没有宽高就不会显示了吧？

**Comment by 335296558** [comment]
> 由于插件有默认的size，导致以下svg的rect被错误替换了，能否加入一个参数跳过设置宽高呢，或者size不要给默认值？ `<svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve"> <rect x="0.5" y="0.5" class="st0" width="15" height="15"/> <path class="st1" d="M8.7,3.6l1,2C9.7,5.7,9.9,5.8,10,5.9l2.2,0.3c0.4,0.1,0.5,0.5,0.2,0.7l-1.6,1.6c-0.1,0.1-0.1,0.2-0.1,0.4 l0.4,2.2c0.1,0.4-0.3,0.6-0.6,0.5l-2-1.1c-0.1-0.1-0.3-0.1-0.4,0l-2,1.1c-0.3,0.2-0.7-0.1-0.6-0.5l0.4-2.2c0-0.1,0-0.3-0.1-0.4 L4.1,6.9C3.8,6.7,3.9,6.2,4.3,6.2l2.2-0.3c0.1,0,0.3-0.1,0.3-0.2l1-2C8,3.3,8.5,3.3,8.7,3.6z"/> </svg>`

v1.1.6版本开始，只有svg标签才会被设置宽高，但如果:size="false" 将不对svg设置宽高，但要注意：如果svg本身就没有宽高，那可能它不会被显示出来
