### ISSUE TITLE
options dir 居然没有用到

### ISSUE THREAD

**Issue by twoer** [335296558/vite-plugin-vue-svg-icons#5]
准备重新设置目录的，发现还是报错，看了一下源码，压根没用；

**Comment by 335296558** [comment]
> 准备重新目录的，发现还是报错，看了一下源码，压根没用；

修复了哈

**Comment by twoer** [comment]
另外可考虑过引入 svgo ？

**Comment by 335296558** [comment]
> 另外可考虑过引入 [svgo](https://github.com/svg/svgo) ?

好建议，我有空看一下svgo它精简过的代码后是怎么样的情况后先。
